### PR TITLE
[model][client] Custom metadata model registration

### LINKED ISSUE #52: Wrong attribute name for deleteTime
The deletionTime attribute in Entity should be deleteTime, otherwise it will be converted on the server side into a UDP instead.

### LINKED ISSUE #53: Update SDK for managed custom properties
In Navigator 2.6 we're adding the ability to create managed custom properties that have a type and comes with validation constraints. These properties belong to namespaces and are associated with various meta-classes (i.e., hdfs entities, Hive tables, etc).

### PR DESCRIPTION
**Pull request by changhiskhan**
To support type custom fields and richer metadata modeling, we implement
the registerModels feature of the SDK to convert @MClass models into JSON
to be registered with the server. We're using the new custom property feature
in Navigator 2.6 to create managed custom properties that have a type and 
allow validation constraints to be specified. These properties belong to namespaces 
and are associated with various meta-classes (i.e., hdfs entities,
Hive tables, etc).

Closes #52 
Closes #53 

TODO:

- [x] Fix hard coded namespace
- [x] Make API version an explicit config variable
- [x] Fix broken tests
- [x] Clean up examples
- [x] documentation

### CODE REVIEW

File: client/src/main/java/com/cloudera/nav/sdk/client/writer/serde/EntitySerializer.java [hunk 1]
```diff
@@ -31,8 +42,32 @@ public EntitySerializer(MClassRegistry registry) {
...
+    }
     String modelName = t.getClass().getAnnotation(MClass.class).model();
     jg.writeStringField("internalType", modelName);
+    jg.writeStringField("metaClassName", modelName);
+    jg.writeObjectField("customProperties", customProperties);
+  }
+
+  private void addCustom(Map<String, Map<String, Object>> customProperties,
+                         MPropertyEntry prop, Entity t) {
+    String namespace = "example"; // FIXME
```
Comment (changhiskhan) [inline client/src/main/java/com/cloudera/nav/sdk/client/writer/serde/EntitySerializer.java]: This needs to be supplied from the config or the Entity
